pool:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@0
  displayName: 'Build a container image'
  inputs:
    azureSubscription: 'Visual Studio Enterprise'
    azureContainerRegistry: '{"loginServer":"jdacr10.azurecr.io", "id" : "/subscriptions/2f6472b1-f49b-4d88-87cf-30d3083413b5/resourceGroups/jdacr/providers/Microsoft.ContainerRegistry/registries/jdacr10"}'

- task: Docker@0
  displayName: 'Push a container image'
  inputs:
    azureSubscription: 'Visual Studio Enterprise'
    action: 'Push an image'

- task: HelmInstaller@0
  displayName: 'Install Helm 2.9.1'
  inputs:
    kubectlVersion: 1.10.3
    checkLatestKubectl: false

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: 'charts/spring-boot-websocket-chat-demo'
    save: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
