pool:
  name: jldeenlinux

stages:
- stage: Build
  displayName: Kubernetes Build
  jobs:
  - job: BuildJob
    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: '1ed2758d-9812-4322-9de3-ee5cdd989ab4'
- stage: deploy
